name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # nightly sync @ 06:00 UTC

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install jq (for sync script)
        run: sudo apt-get update && sudo apt-get install -y jq

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - name: Install deps
        working-directory: site
        run: npm ci

      - name: Sync repo docs (READMEs + /docs folders)
        working-directory: site
        env:
          # If you hit API rate limits, create a PAT named DOCS_SYNC_TOKEN and switch to that secret:
          # GITHUB_TOKEN: ${{ secrets.DOCS_SYNC_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/sync-repo-docs.sh

      - name: Build site
        working-directory: site
        run: npm run build

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
